apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: susantaadak/test-backend:v1
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: mongodb://admin:password123@mongo.test.svc.cluster.local:27017/formdb?authSource=admin
