apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: test
type: Opaque
data:
  mongo-user: YWRtaW4=              # admin
  mongo-password: cGFzc3dvcmQxMjM=  # password123
  mongo-database: Zm9ybWRi          # formdb
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvLnRlc3Quc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZm9ybWRiP2F1dGhTb3VyY2U9YWRtaW4=  # mongodb://admin: