apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: test
type: Opaque
data:
  mongo-user: YWRtaW4=              # admin
  mongo-password: cGFzc3dvcmQxMjM=  # password123
  mongo-database: Zm9ybWRi          # formdb
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvOjI3MDE3L2Zvcm1kYj9hdXRoU291cmNlPWFkbWluCg== # mongodb://admin:password123@mongo:27017/formdb?authSource=admin